export const blogList = [
    {
      id: 1,
      title: '7 CSS tools you should be using ',
      category: 'development',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'NICK RUSLAN',
      cover: '/assets/images/blog-1.webp',
      createdAt: 'June 03, 2023',
      done:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
      dtwo:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur delectus perspiciatis aut? Necessitatibus, obcaecati unde! Vero hic architecto laborum ipsum possimus. Totam distinctio sunt accusamus voluptas fugit. Fugiat, corporis magnam! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam dolorem sunt magnam perspiciatis ducimus quae pariatur temporibus, modi aperiam distinctio, fuga optio quo, delectus quaerat accusamus soluta. Id, perferendis aliquam.",
      dthree:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
      },
    {
      id: 2,
      title: 'Milan Places That Highlight The City',
      category: 'travel',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'NICK RUSLAN',
      cover: '/assets/images/blog-2.webp',
      createdAt: 'June 03, 2023',
      done:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
      dtwo:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur delectus perspiciatis aut? Necessitatibus, obcaecati unde! Vero hic architecto laborum ipsum possimus. Totam distinctio sunt accusamus voluptas fugit. Fugiat, corporis magnam! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam dolorem sunt magnam perspiciatis ducimus quae pariatur temporibus, modi aperiam distinctio, fuga optio quo, delectus quaerat accusamus soluta. Id, perferendis aliquam.",
      dthree:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
          },
    {
      id: 3,
      title: 'Online Shopping – An Alternative to Shopping in the Mall',
      category: 'shopping',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'NICK RUSLAN',
      cover: '/assets/images/blog-3.webp',
      createdAt: 'June 03, 2023',
      done:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
      dtwo:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur delectus perspiciatis aut? Necessitatibus, obcaecati unde! Vero hic architecto laborum ipsum possimus. Totam distinctio sunt accusamus voluptas fugit. Fugiat, corporis magnam! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam dolorem sunt magnam perspiciatis ducimus quae pariatur temporibus, modi aperiam distinctio, fuga optio quo, delectus quaerat accusamus soluta. Id, perferendis aliquam.",
      dthree:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
        },
    {
      id: 4,
      title: 'ADVENTURE IN YOU',
      category: 'adventure',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'NICK RUSLAN',
      cover: '/assets/images/blog-4.webp',
      createdAt: 'June 03, 2023',
      done:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
      dtwo:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur delectus perspiciatis aut? Necessitatibus, obcaecati unde! Vero hic architecto laborum ipsum possimus. Totam distinctio sunt accusamus voluptas fugit. Fugiat, corporis magnam! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam dolorem sunt magnam perspiciatis ducimus quae pariatur temporibus, modi aperiam distinctio, fuga optio quo, delectus quaerat accusamus soluta. Id, perferendis aliquam.",
      dthree:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
        },
    {
      id: 5,
      title: 'Loaded BBQ Baked Potatoes',
      category: 'cooking',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",  
      authorName: 'NICK RUSLAN',
      cover: '/assets/images/blog-5.webp',
      createdAt: 'June 03, 2023',
      done:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
      dtwo:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur delectus perspiciatis aut? Necessitatibus, obcaecati unde! Vero hic architecto laborum ipsum possimus. Totam distinctio sunt accusamus voluptas fugit. Fugiat, corporis magnam! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam dolorem sunt magnam perspiciatis ducimus quae pariatur temporibus, modi aperiam distinctio, fuga optio quo, delectus quaerat accusamus soluta. Id, perferendis aliquam.",
      dthree:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
       },
    {
      id: 6,
      title: 'Beyond the Beach',
      category: 'travel',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'NICK RUSLAN',
      cover: '/assets/images/blog-6.webp',
      createdAt: 'June 03, 2023',
      done:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
      dtwo:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur delectus perspiciatis aut? Necessitatibus, obcaecati unde! Vero hic architecto laborum ipsum possimus. Totam distinctio sunt accusamus voluptas fugit. Fugiat, corporis magnam! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam dolorem sunt magnam perspiciatis ducimus quae pariatur temporibus, modi aperiam distinctio, fuga optio quo, delectus quaerat accusamus soluta. Id, perferendis aliquam.",
      dthree:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste tenetur maiores necessitatibus! Ea quia omnis voluptatibus odio nobis maxime quam tenetur, quis, et, quibusdam fuga molestias blanditiis beatae sapiente! Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga molestias deleniti sit, assumenda expedita quod reprehenderit dicta, reiciendis nobis ratione architecto perferendis facilis magnam voluptate voluptas itaque enim numquam quisquam?",
              },
  ];